import "~/styles/globals.css";
import "../styles/common.css"
import { type Metadata } from "next";
import CustomThemeProvider from "./_components/CustomThemeProvider"; 
import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <SessionProvider>
    <html lang="en">
      <body className="bg-gray-100 dark:bg-gray-900 text-black dark:text-white">
        <CustomThemeProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </CustomThemeProvider>
      </body>
    </html>
    </SessionProvider>
  );
}
